// Auto-generated by OpenLane
module top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input data_in,
  input start,
  output ready,
  output running,
  output temp_reset,
  output[6:0] count_out
);
endmodule
